name: driverme_app
description: DriverMe - Ứng dụng thuê tài xế

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^13.0.0

  # Storage
  shared_preferences: ^2.2.2

  # Network
  http: ^1.5.0
  socket_io_client: ^2.0.3+1

  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true